name: Attach Release Asset

on:
  release:
    types: [published, prereleased, released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (required for manual run)'
        required: true

permissions:
  contents: write

jobs:
  attach-release-asset:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick

      # - name: Get tag
      #   id: tag
      #   run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Determine the tag name to use
      - name: Get tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      # Determine the zip file name
      - name: Get Zip File Name
        id: zip_filename
        run: echo "name=${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT

      # Create a scoped package
      - name: Create scoped package
        run: |
          composer create-scoped-release

      - name: Create ZIP file wp-thumbhash-scoped
        run: |
          cd wp-thumbhash-scoped
          zip -r "/tmp/${{ steps.zip_filename.outputs.name }}.zip" . # Zip the contents of the subfolder
          cd ..

      - name: Debug information
        run: |
          php --version
          composer --version
          echo "Captured tag: ${{ steps.tag.outputs.tag }}"
          echo "Repo name: ${{ github.event.repository.name }}"
          echo "ZIP name: ${{ steps.zip_filename.outputs.name }}"
          ls -la

      # Upload the ZIP file as a release asset (only during release events)
      - name: Upload release asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/${{ steps.zip_filename.outputs.name }}.zip
          asset_name: ${{ steps.zip_filename.outputs.name }}.zip
          asset_content_type: application/zip