name: Attach Release Asset

on:
  release:
    types: [published, prereleased, released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (required for manual run)'
        required: true

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick

      # - name: Get tag
      #   id: tag
      #   run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Determine the tag name to use
      - name: Set tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      # (Optional) Install dependencies if needed
      - name: Install dependencies
        run: |
          composer create-scoped-release

      - name: Debug information
        run: |
          php --version
          composer --version
          echo "Captured tag: ${{ steps.tag.outputs.tag }}"

      # - name: Create ZIP file wp-thumbhash-scoped
      #   run: |
      #     mkdir -p build
      #     ZIP_FILENAME="wp-thumbhash-${TAG_NAME}.zip"
      #     cd wp-thumbhash-scoped
      #     zip -r "../$ZIP_FILENAME" . # Zip the contents of the subfolder
      #     cd ..

      # # Upload the ZIP file as a release asset (only during release events)
      # - name: Upload release asset
      #   if: github.event_name == 'release'
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: wp-thumbhash-${TAG_NAME}.zip
      #     asset_name: wp-thumbhash-${TAG_NAME}.zip
      #     asset_content_type: application/zip