name: Attach Release Asset

on:
  release:
    types: [published, prereleased, released, edited]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (required for manual run)'
        required: true

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick

      # (Optional) Install dependencies if needed
      - name: Install dependencies
        run: |
          composer create-scoped-release

      - name: Debug information
        run: |
          php --version
          composer --version

      # Determine the tag name to use
      - name: Set tag name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Create ZIP file wp-thumbhash-scoped
        run: |
          mkdir -p build
          ZIP_FILENAME="wp-thumbhash-${TAG_NAME}.zip"
          cd wp-thumbhash-scoped
          zip -r "../build/$ZIP_FILENAME" . # Zip the contents of the subfolder

      # Upload the ZIP file as a release asset (only during release events)
      - name: Upload release asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/my-release-${TAG_NAME}.zip
          asset_name: my-release-${TAG_NAME}.zip
          asset_content_type: application/zip